networks:
  app-network:
    driver: bridge

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    
    container_name: portfolio-frontend
    restart: unless-stopped
    expose:
      - "3000"
    networks:
      - app-network
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile

    container_name: portfolio-backend
    restart: unless-stopped
    expose:
      -  "8000"
    environment:
      - NODE_ENV=production
      - API_PORT=8000
    networks:
    - app-network
  
  nginx:
    image: nginx:alpine
    container_name: portfolio-nginx
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - app-network
    depends_on:
      - frontend
      - backend