---
- name: Setup Ubuntu VM for DevOps Portfolio Project
  hosts: dev-server
  become: true
  gather_facts: true

  vars:
    project_dir: "/opt/portfolio"
    git_repo_url: "https://github.com/cicero-w/devops-portfolio-project.git"
    git_branch: "develop"

  tasks:
    - name: Update and upgrade apt packages
      apt:
        update_cache: true
        upgrade: dist
        cache_valid_time: 3600
      tags: [system]

    - name: Install required system packages for Docker repository
      apt:
        name: [ca-certificates, curl, gnupg]
        state: present
      tags: [docker, system]

    - name: Create keyrings directory for apt
      file:
        path: /etc/apt/keyrings
        state: directory
        mode: '0755'
      tags: [docker]

    - name: Add Docker official GPG key
      get_url:
        url: https://download.docker.com/linux/ubuntu/gpg
        dest: /etc/apt/keyrings/docker.asc
        mode: '0644'
        force: true
      tags: [docker]

    - name: Detect Ubuntu release codename
      set_fact:
        ubuntu_codename: "{{ ansible_distribution_release }}"

    - name: Detect architecture
      set_fact:
        docker_arch: "{{ 'arm64' if ansible_architecture == 'aarch64' else 'amd64' }}"

    - name: Add Docker repository
      apt_repository:
        repo: "deb [arch={{ docker_arch }} signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu {{ ubuntu_codename }} stable"
        state: present
        filename: docker
      tags: [docker]

    - name: Update apt cache after adding Docker repo
      apt:
        update_cache: yes
      tags: [docker]

    - name: Install Docker packages
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-buildx-plugin
          - docker-compose-plugin
        state: present
        update_cache: true
      tags: [docker]

    - name: Add deployment user to the docker group
      user:
        name: "{{ ansible_user }}"
        groups: docker
        append: true
      tags: [docker]

    - name: Reset SSH connection to apply group changes
      meta: reset_connection
      tags: [docker]

    - name: Start and enable Docker service
      systemd:
        name: docker
        state: started
        enabled: true
      tags: [docker]

    - name: Install Git
      apt:
        name: git
        state: present
      tags: [git]

    - name: Create project directory
      file:
        path: "{{ project_dir }}"
        state: directory
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: '0755'
      tags: [project]

    - name: Clone project repository
      git:
        repo: "{{ git_repo_url }}"
        dest: "{{ project_dir }}"
        version: "{{ git_branch }}"
        force: true
      become: false
      tags: [project]

    - name: Deploy application with Docker Compose
      community.docker.docker_compose_v2:
        project_src: "{{ project_dir }}"
        files:
          - docker-compose.prod.yml
        state: present
        pull: always
        restarted: true
      become: false
      register: compose_result
      tags: [deploy]

    - name: Display deployment results
      debug:
        var: compose_result
      tags: [deploy]