name: Trivy Scan

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 0 * * 0'

jobs:
  trivy-scan:
    name: Scan with Trivy
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Scan Backend folder
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          path: './backend'
          format: 'sarif'
          output: 'trivy-backend.sarif'

      - name: Scan Frontend folder
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          path: './frontend'
          format: 'sarif'
          output: 'trivy-frontend.sarif'

      - name: Upload Trivy Backend results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: 'trivy-backend.sarif'

      - name: Upload Trivy Frontend results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: 'trivy-frontend.sarif'
